---
fullname: File Synchroniser
shortname: file-sync
organization: liyishuai
synopsis: File synchroniser specification in Coq
description: Coq formalisation of the Unison file synchroniser
authors:
  - name: Yishuai Li
    email: liyishuai.lys@alibaba-inc.com
license:
  fullname: Mozilla Public License 2.0
  identifier: MPL-2.0
namespace: FileSync
opam-file-maintainer: 'Yishuai Li <liyishuai.lys@alibaba-inc.com>'
ci_extra_dev: true
supported_coq_versions:
  text: 8.14 or later
  opam: '{ >= "8.14~" }'
supported_ocaml_versions:
  text: 4.12 or later
  opam: '{ >= "4.12" }'
dependencies:
  - description: '[SimpleIO](https://github.com/Lysxia/coq-simple-io)'
    opam:
      name: coq-simple-io
      version: '{ >= "1.8.0" }'
  - description: '[AsyncTest](https://github.com/liyishuai/coq-async-test)'
    opam:
      name: coq-async-test
  - description: '[OCamlbuild](https://github.com/ocaml/ocamlbuild)'
    opam:
      name: ocamlbuild
  - description: '[Fileutils](https://github.com/gildor478/ocaml-fileutils)'
    opam:
      name: fileutils
  - description: '[Unison](https://www.cis.upenn.edu/~bcpierce/unison/)'
    opam:
      name: unison
      version: '{ with-test }'
action: true
action_appendix: |2-
            export: 'OPAMWITHTEST'
          env:
            OPAMWITHTEST: true
tested_coq_opam_versions:
  - version: 'dev'
  - version: '8.16'
  - version: '8.15-ocaml-4.14-flambda'
  - version: '8.14-ocaml-4.14-flambda'
test_target: test
install_flag: 'INSTALLDIR=%{bin}%'
