---
fullname: File Synchroniser
shortname: file-sync
organization: liyishuai
synopsis: File synchroniser specification in Coq
description: Coq formalisation of the Unison file synchroniser
authors:
  - name: Yishuai Li
    email: yishuai@cis.upenn.edu
license:
  fullname: Mozilla Public License 2.0
  identifier: MPL-2.0
namespace: FileSync
opam-file-maintainer: 'Yishuai Li <yishuai@cis.upenn.edu>'
ci_extra_dev: true
supported_coq_versions:
  text: 8.12 or later
  opam: '{ >= "8.12~" }'
supported_ocaml_versions:
  text: 4.07 or later
  opam: '{ >= "4.07" }'
dependencies:
  - description: '[AsyncTest](https://github.com/liyishuai/coq-async-test)'
    opam:
      name: coq-async-test
  - description: '[OCamlbuild](https://github.com/ocaml/ocamlbuild)'
    opam:
      name: ocamlbuild
  - description: '[Fileutils](https://github.com/gildor478/ocaml-fileutils)'
    opam:
      name: fileutils
action: true
tested_coq_opam_versions:
  - version: '8.15-ocaml-4.12-flambda'
  - version: '8.14-ocaml-4.12-flambda'
  - version: '8.13-ocaml-4.12-flambda'
  - version: '8.12-ocaml-4.11-flambda'
