---
fullname: File Synchroniser
shortname: file-sync
organization: liyishuai
synopsis: File synchroniser specification in Coq
description: Coq formalisation of the Unison file synchroniser
authors:
  - name: Yishuai Li
    email: yishuai@cis.upenn.edu
license:
  fullname: Mozilla Public License 2.0
  identifier: MPL-2.0
namespace: FileSync
opam-file-maintainer: 'Yishuai Li <yishuai@cis.upenn.edu>'
supported_coq_versions:
  text: 8.9 or later
  opam: '{ >= "8.9~" }'
dependencies:
  - description: '[Cérès](https://github.com/Lysxia/coq-ceres)'
    opam:
      name: coq-ceres
  - description: '[ITreeIO](https://github.com/Lysxia/coq-itree-io)'
    opam:
      name: coq-itree-io
action: true
tested_coq_opam_versions:
  - version: '8.14'
  - version: '8.13'
  - version: '8.12'
  - version: '8.11'
  - version: '8.10'
  - version: '8.9'
